public class MimeTypes {
    public static final String PDF = "application/pdf";
    public static final String HTML = "text/html";
    public static final String COREL = "application/envoy";
    public static final String FRACTAL = "application/fractals";
    public static final String WINDOWS = "application/futuresplash";
    public static final String ATARI = "application/internet-property-stream";
    public static final String BINHEX = "application/mac-binhex40";
    public static final String WORD = "application/msword";
    public static final String JAVA = "application/octet-stream";
    public static final String DISK = "application/octet-stream";
    public static final String EXECUTABLE = "application/octet-stream";
    public static final String LHARC = "application/octet-stream";
    public static final String LZH = "application/octet-stream";
    public static final String CALS = "application/oda";
    public static final String ACTIVEX = "application/olescript";
    public static final String ACROBAT = "application/pdf";
    public static final String CERTIFICATE = "application/pkix-crl";
    public static final String POSTSCRIPT = "application/postscript";
    public static final String SET = "application/set-registration-initiation";
    public static final String EXCEL = "application/vnd.ms-excel";
    public static final String OUTLOOK = "application/vnd.ms-outlook";
    public static final String SERIALIZED = "application/vnd.ms-pkicertstore";
    public static final String STEREOLITHOGRAPHY = "application/vnd.ms-pkistl";
    public static final String POWERPOINT = "application/vnd.ms-powerpoint";
    public static final String WORDPERFECT = "application/vnd.ms-works";
    public static final String MICROSOFT = "application/vnd.ms-works";
    public static final String BINARY = "application/x-bcpio";
    public static final String UNIX = "application/x-compress";
    public static final String GZIPPED = "application/x-compressed";
    public static final String PHOTOSHOP = "application/x-csh";
    public static final String KODAK = "application/x-director";
    public static final String ADOBE = "application/x-director";
    public static final String MACROMEDIA = "application/x-director";
    public static final String DEVICE = "application/x-dvi";
    public static final String GNU = "application/x-gtar";
    public static final String HIERARCHICAL = "application/x-hdf";
    public static final String INTERNET = "application/x-internet-signup";
    public static final String IIS = "application/x-internet-signup";
    public static final String ARC = "application/x-iphone";
    public static final String JAVASCRIPT = "application/x-javascript";
    public static final String LATEX = "application/x-latex";
    public static final String CRAZYTALK = "application/x-msclip";
    public static final String DYNAMIC = "application/x-msdownload";
    public static final String STEUER2001 = "application/x-msmediaview";
    public static final String MULTIMEDIA = "application/x-msmediaview";
    public static final String TURBO = "application/x-msschedule";
    public static final String FTR = "application/x-msterminal";
    public static final String COMPUTABLE = "application/x-netcdf";
    public static final String MASTERCAM = "application/x-netcdf";
    public static final String MSX = "application/x-perfmon";
    public static final String PERFORMANCE = "application/x-perfmon";
    public static final String PROCESS = "application/x-perfmon";
    public static final String AVID = "application/x-perfmon";
    public static final String PEGASUS = "application/x-perfmon";
    public static final String PERSONAL = "application/x-pkcs12";
    public static final String PKCS = "application/x-pkcs12";
    public static final String SOFTWARE = "application/x-pkcs7-certificates";
    public static final String DIGITALLY = "application/x-pkcs7-mime";
    public static final String BASH = "application/x-sh";
    public static final String FLASH = "application/x-shockwave-flash";
    public static final String STUFFIT = "application/x-stuffit";
    public static final String SYSTEM = "application/x-sv4cpio";
    public static final String CONSOLIDATED = "application/x-tar";
    public static final String TCL = "application/x-tcl";
    public static final String UNFORMATTED = "application/x-troff";
    public static final String TURING = "application/x-troff";
    public static final String TOMERAIDER = "application/x-troff";
    public static final String README = "application/x-troff-me";
    public static final String TDS = "application/x-troff-ms";
    public static final String UNIFORM = "application/x-ustar";
    public static final String SOURCE = "application/x-wais-source";
    public static final String SECURITY = "application/x-x509-ca-cert";
    public static final String DER = "application/x-x509-ca-cert";
    public static final String PUBLIC = "application/ynd.ms-pkipko";
    public static final String ZIPPED = "application/zip";
    public static final String AUDIO = "audio/basic";
    public static final String SOUND = "audio/basic";
    public static final String MIDI = "audio/mid";
    public static final String MEDIA = "audio/mid";
    public static final String MP3 = "audio/mpeg";
    public static final String COMPRESSED = "audio/x-aiff";
    public static final String REAL = "audio/x-pn-realaudio";
    public static final String WAVE = "audio/x-wav";
    public static final String BITMAP = "image/bmp";
    public static final String COMPILED = "image/cis-cod";
    public static final String GRAPHIC = "image/gif";
    public static final String IMAGE = "image/ief";
    public static final String JPEG = "image/jpeg";
    public static final String SCALABLE = "image/svg+xml";
    public static final String TIF = "image/tiff";
    public static final String SUN = "image/x-cmu-raster";
    public static final String ICON = "image/x-icon";
    public static final String PORTABLE = "image/x-portable-anymap";
    public static final String RGB = "image/x-rgb";
    public static final String X11 = "image/x-xbitmap";
    public static final String X_WINDOWS = "image/x-xwindowdump";
    public static final String MHTML = "message/rfc822";
    public static final String MIME = "message/rfc822";
    public static final String CASCADING = "text/css";
    public static final String H_323 = "text/h323";
    public static final String EXCHANGE = "text/html";
    public static final String NETMEETING = "text/iuls";
    public static final String BASIC = "text/plain";
    public static final String C = "text/plain";
    public static final String CPP = "text/plain";
    public static final String TEXT = "text/plain";
    public static final String RICH = "text/richtext";
    public static final String SCITEXT = "text/scriptlet";
    public static final String TAB = "text/tab-separated-values";
    public static final String HYPERTEXT = "text/webviewhtml";
    public static final String TEX = "text/x-setext";
    public static final String VCARD = "text/x-vcard";
    public static final String APPLE = "video/quicktime";
    public static final String LOGOS = "video/x-la-asf";
    public static final String STREAMING = "video/x-la-asf";
    public static final String ADVANCED = "video/x-ms-asf";
    public static final String ACTIONSCRIPT = "video/x-ms-asf";
    public static final String FLARE = "x-world/x-vrml";
    public static final String VRML = "x-world/x-vrml";
    public static final String REALITY = "x-world/x-vrml";

    /**
     * Obtains the correspondant MIME Type of a given extension
     * Note: The method is implemented with if stataments due to the original project runs in a lower version than 7
     * @param fileExtension The extension of a file
     * @return The MIME Type in a string
     */
    public static final String getMimeType(String fileExtension) {
        String ext = fileExtension.toLowerCase();

        if (ext.equals("pdf")) return PDF;
        else if (ext.equals("html") || ext.equals("htm") || ext.equals("stm")) return HTML;
        else if (ext.equals("evy")) return COREL;
        else if (ext.equals("fif")) return FRACTAL;
        else if (ext.equals("spl")) return WINDOWS;
        else if (ext.equals("hta")) return HTML;
        else if (ext.equals("acx")) return ATARI;
        else if (ext.equals("hqx")) return BINHEX;
        else if (ext.equals("doc")) return WORD;
        else if (ext.equals("dot")) return WORD;
        else if (ext.equals("bin")) return BINARY;
        else if (ext.equals("class")) return JAVA;
        else if (ext.equals("dms")) return DISK;
        else if (ext.equals("exe")) return EXECUTABLE;
        else if (ext.equals("lha")) return LHARC;
        else if (ext.equals("lzh")) return LZH;
        else if (ext.equals("oda")) return CALS;
        else if (ext.equals("axs")) return ACTIVEX;
        else if (ext.equals("pdf")) return ACROBAT;
        else if (ext.equals("prf")) return OUTLOOK;
        else if (ext.equals("p10")) return CERTIFICATE;
        else if (ext.equals("crl")) return CERTIFICATE;
        else if (ext.equals("ai")) return ADOBE;
        else if (ext.equals("eps")) return POSTSCRIPT;
        else if (ext.equals("ps")) return POSTSCRIPT;
        else if (ext.equals("rtf")) return RICH;
        else if (ext.equals("setpay")) return SET;
        else if (ext.equals("setreg")) return SET;
        else if (ext.equals("xla")) return EXCEL;
        else if (ext.equals("xlc")) return EXCEL;
        else if (ext.equals("xlm")) return EXCEL;
        else if (ext.equals("xls")) return EXCEL;
        else if (ext.equals("xlt")) return EXCEL;
        else if (ext.equals("xlw")) return EXCEL;
        else if (ext.equals("xlsx")) return EXCEL;
        else if (ext.equals("msg")) return OUTLOOK;
        else if (ext.equals("sst")) return SERIALIZED;
        else if (ext.equals("cat")) return WINDOWS;
        else if (ext.equals("stl")) return STEREOLITHOGRAPHY;
        else if (ext.equals("pot")) return POWERPOINT;
        else if (ext.equals("pps")) return POWERPOINT;
        else if (ext.equals("ppt")) return POWERPOINT;
        else if (ext.equals("mpp")) return MICROSOFT;
        else if (ext.equals("wcm")) return WORDPERFECT;
        else if (ext.equals("wdb")) return MICROSOFT;
        else if (ext.equals("wks")) return MICROSOFT;
        else if (ext.equals("wps")) return MICROSOFT;
        else if (ext.equals("hlp")) return WINDOWS;
        else if (ext.equals("bcpio")) return BINARY;
        else if (ext.equals("cdf")) return COMPUTABLE;
        else if (ext.equals("z")) return UNIX;
        else if (ext.equals("tgz")) return GZIPPED;
        else if (ext.equals("cpio")) return UNIX;
        else if (ext.equals("csh")) return PHOTOSHOP;
        else if (ext.equals("dcr")) return KODAK;
        else if (ext.equals("dir")) return ADOBE;
        else if (ext.equals("dxr")) return MACROMEDIA;
        else if (ext.equals("dvi")) return DEVICE;
        else if (ext.equals("gtar")) return GNU;
        else if (ext.equals("gz")) return GNU;
        else if (ext.equals("hdf")) return HIERARCHICAL;
        else if (ext.equals("ins")) return INTERNET;
        else if (ext.equals("isp")) return IIS;
        else if (ext.equals("iii")) return ARC;
        else if (ext.equals("js")) return JAVASCRIPT;
        else if (ext.equals("latex")) return LATEX;
        else if (ext.equals("mdb")) return MICROSOFT;
        else if (ext.equals("crd")) return WINDOWS;
        else if (ext.equals("clp")) return CRAZYTALK;
        else if (ext.equals("dll")) return DYNAMIC;
        else if (ext.equals("m13")) return MICROSOFT;
        else if (ext.equals("m14")) return STEUER2001;
        else if (ext.equals("mvb")) return MULTIMEDIA;
        else if (ext.equals("wmf")) return WINDOWS;
        else if (ext.equals("mny")) return MICROSOFT;
        else if (ext.equals("pub")) return MICROSOFT;
        else if (ext.equals("scd")) return TURBO;
        else if (ext.equals("trm")) return FTR;
        else if (ext.equals("wri")) return MICROSOFT;
        else if (ext.equals("cdf")) return COMPUTABLE;
        else if (ext.equals("nc")) return MASTERCAM;
        else if (ext.equals("pma")) return MSX;
        else if (ext.equals("pmc")) return PERFORMANCE;
        else if (ext.equals("pml")) return PROCESS;
        else if (ext.equals("pmr")) return AVID;
        else if (ext.equals("pmw")) return PEGASUS;
        else if (ext.equals("p12")) return PERSONAL;
        else if (ext.equals("pfx")) return PKCS;
        else if (ext.equals("p7b")) return PKCS;
        else if (ext.equals("spc")) return SOFTWARE;
        else if (ext.equals("p7r")) return CERTIFICATE;
        else if (ext.equals("p7c")) return PKCS;
        else if (ext.equals("p7m")) return DIGITALLY;
        else if (ext.equals("p7s")) return DIGITALLY;
        else if (ext.equals("sh")) return BASH;
        else if (ext.equals("shar")) return UNIX;
        else if (ext.equals("swf")) return FLASH;
        else if (ext.equals("sit")) return STUFFIT;
        else if (ext.equals("sv4cpio")) return SYSTEM;
        else if (ext.equals("sv4crc")) return SYSTEM;
        else if (ext.equals("tar")) return CONSOLIDATED;
        else if (ext.equals("tcl")) return TCL;
        else if (ext.equals("tex")) return LATEX;
        else if (ext.equals("texi")) return LATEX;
        else if (ext.equals("texinfo")) return LATEX;
        else if (ext.equals("roff")) return UNFORMATTED;
        else if (ext.equals("t")) return TURING;
        else if (ext.equals("tr")) return TOMERAIDER;
        else if (ext.equals("man")) return UNIX;
        else if (ext.equals("me")) return README;
        else if (ext.equals("ms")) return TDS;
        else if (ext.equals("ustar")) return UNIFORM;
        else if (ext.equals("src")) return SOURCE;
        else if (ext.equals("cer")) return INTERNET;
        else if (ext.equals("crt")) return SECURITY;
        else if (ext.equals("der")) return DER;
        else if (ext.equals("pko")) return PUBLIC;
        else if (ext.equals("zip")) return ZIPPED;
        else if (ext.equals("au")) return AUDIO;
        else if (ext.equals("snd")) return SOUND;
        else if (ext.equals("mid")) return MIDI;
        else if (ext.equals("rmi")) return MEDIA;
        else if (ext.equals("mp3")) return MP3;
        else if (ext.equals("aif")) return AUDIO;
        else if (ext.equals("aifc")) return COMPRESSED;
        else if (ext.equals("aiff")) return AUDIO;
        else if (ext.equals("m3u")) return MEDIA;
        else if (ext.equals("ra")) return REAL;
        else if (ext.equals("ram")) return REAL;
        else if (ext.equals("wav")) return WAVE;
        else if (ext.equals("bmp")) return BITMAP;
        else if (ext.equals("cod")) return COMPILED;
        else if (ext.equals("gif")) return GRAPHIC;
        else if (ext.equals("ief")) return IMAGE;
        else if (ext.equals("jpe")) return JPEG;
        else if (ext.equals("jpeg")) return JPEG;
        else if (ext.equals("jpg")) return JPEG;
        else if (ext.equals("jfif")) return JPEG;
        else if (ext.equals("svg")) return SCALABLE;
        else if (ext.equals("tif")) return TIF;
        else if (ext.equals("tiff")) return TIF;
        else if (ext.equals("ras")) return SUN;
        else if (ext.equals("cmx")) return COREL;
        else if (ext.equals("ico")) return ICON;
        else if (ext.equals("pnm")) return PORTABLE;
        else if (ext.equals("pbm")) return PORTABLE;
        else if (ext.equals("pgm")) return PORTABLE;
        else if (ext.equals("ppm")) return PORTABLE;
        else if (ext.equals("rgb")) return RGB;
        else if (ext.equals("xbm")) return X11;
        else if (ext.equals("xpm")) return X11;
        else if (ext.equals("mht")) return MHTML;
        else if (ext.equals("mhtml")) return MIME;
        else if (ext.equals("nws")) return WINDOWS;
        else if (ext.equals("css")) return CASCADING;
        else if (ext.equals("323")) return H_323;
        else if (ext.equals("htm")) return HTML;
        else if (ext.equals("html")) return HTML;
        else if (ext.equals("stm")) return EXCHANGE;
        else if (ext.equals("uls")) return NETMEETING;
        else if (ext.equals("bas")) return BASIC;
        else if (ext.equals("c")) return C;
        else if (ext.equals("h")) return CPP;
        else if (ext.equals("txt")) return TEXT;
        else if (ext.equals("rtx")) return RICH;
        else if (ext.equals("sct")) return SCITEXT;
        else if (ext.equals("tsv")) return TAB;
        else if (ext.equals("htt")) return HYPERTEXT;
        else if (ext.equals("htc")) return HTML;
        else if (ext.equals("etx")) return TEX;
        else if (ext.equals("vcf")) return VCARD;
        else if (ext.equals("mov")) return APPLE;
        else if (ext.equals("qt")) return APPLE;
        else if (ext.equals("lsf")) return LOGOS;
        else if (ext.equals("lsx")) return STREAMING;
        else if (ext.equals("asf")) return ADVANCED;
        else if (ext.equals("asr")) return ACTIONSCRIPT;
        else if (ext.equals("asx")) return MICROSOFT;
        else if (ext.equals("avi")) return AUDIO;
        else if (ext.equals("movie")) return APPLE;
        else if (ext.equals("flr")) return FLARE;
        else if (ext.equals("vrml")) return VRML;
        else if (ext.equals("wrl")) return VRML;
        else if (ext.equals("wrz")) return COMPRESSED;
        else if (ext.equals("xof")) return REALITY;
        else return null;
    }
}
